use_frameworks!

def shared_pods 
  pod ‘TrySwiftData', :path => '../'
  pod 'RealmSwift' 
end

target ‘TrySwiftData_Tests' do
  shared_pods
end

target 'TrySwiftDataUploader' do
  shared_pods
  pod ‘RealmLoginKit’
end 

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
